default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: contato1
  username: postgres
  password: 1234
  host: db
  port: 5432

test:
  <<: *default
  database: contato1_test
  username: postgres
  password: 1234
  host: db
  port: 5432

production:
  <<: *default
  database: contato1_production
  username: <%= ENV["contato1_DATABASE_USER"] %>
  password: <%= ENV["contato1_DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>