default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_DEVELOPMENT_NAME'] %>
  username: <%= ENV['DB_DEVELOPMENT_USERNAME'] %>
  password: <%= ENV['DB_DEVELOPMENT_PASSWORD'] %>
  host: <%= ENV['DB_DEVELOPMENT_HOST'] %>
  port: <%= ENV['DB_DEVELOPMENT_PORT'] %>

test:
  <<: *default
  database: <%= ENV['DB_TEST_NAME'] %>
  username: <%= ENV['DB_TEST_USERNAME'] %>
  password: <%= ENV['DB_TEST_PASSWORD'] %>
  host: <%= ENV['DB_TEST_HOST'] %>
  port: <%= ENV['DB_TEST_PORT'] %>

production:
  <<: *default
  database: contato1_production
  username: <%= ENV["contato1_DATABASE_USER"] %>
  password: <%= ENV["contato1_DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>